learning_templates/basic/urls.py
from django.conf.urls import url
from basic import views

app_name='basic'

urlpatterns = [
    url(r'^other/$',views.other,name='other'),
    url(r'^relative/$',views.relative,name='relative')

]

learning_templates/learning_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic/',include('basic.urls'))
]

learning_templates/basic/models.py
from django.db import models

# Create your models here.

learning_templates/basic/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context={'text':'hello world','number':100}
    return render(request,'basic/index.html',context)

def other(request):
    return render(request,'basic/other.html')

def relative(request):
    return render(request,'basic/relative_url.html')

learning_templates/templates/basic/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand"><a href="{% url 'index' %}">Brand</a></li>
          <li class="navbar-link"><a href="{% url 'admin:index'%}">Admin</a></li>
          <li class="navbar-link"><a href="{% url 'basic:other'%}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic/index.html
<!DOCTYPE html>
{% extends "basic/base.html"%}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h1>{{text|cut:'world'}}</h1>
    <h1>{{ number |add:"99"}}</h1>
  {% endblock %}

learning_templates/templates/basic/other.html
<!DOCTYPE html>
{% extends "basic/base.html" %}
  {% block body_block %}
      <h1>WELCOME TO OTHER</h1>
      <a href="{% url 'basic:relative'%}">The Relative page</a>
  {% endblock %}

learning_templates/templates/basic/relative_url.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
      <h1>WELCOME TO RELATIVE</h1>
      <a href="{% url 'basic:other' %}">The other page</a>
      <a href="{% url 'admin:index'%}">ADMIN</a>
      <a href="{% url 'index'%}">index</a>
  </body>
</html>